# Generated by Django 6.1.1 on 2026-09-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('url', models.CharField(blank=True, help_text='اتركه فارغاً لاستخدام اسم الرابط', max_length=200, verbose_name='الرابط المباشر')),
                ('url_name', models.CharField(blank=True, help_text='اسم الرابط في Django (مثال: ranks:index)', max_length=100, verbose_name='اسم رابط Django')),
                ('icon', models.CharField(default='fa-link', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'رابط سريع',
                'verbose_name_plural': 'الروابط السريعة',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(choices=[('fa-file-signature', '📝 التقديم الإلكتروني'), ('fa-list-ol', '🎯 ترتيب الرغبات'), ('fa-award', '🏆 المنح الدراسية'), ('fa-certificate', '📜 الشهادات والتوثيق'), ('fa-graduation-cap', '🎓 الجامعات'), ('fa-book', '📚 الكورسات'), ('fa-envelope', '📧 اتصل بنا')], default='fa-graduation-cap', max_length=50, verbose_name='الأيقونة')),
                ('url_name', models.CharField(help_text='اسم الرابط (مثال: admission:index)', max_length=100, verbose_name='اسم الرابط')),
                ('is_active', models.BooleanField(default=True, help_text='إذا كان غير مفعل، يظهر "قريباً"', verbose_name='مفعّل')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='توب سينير', max_length=100, verbose_name='اسم الموقع')),
                ('site_tagline', models.CharField(default='منصّتي للمنح والخدمات الأكاديمية', max_length=200, verbose_name='الشعار الفرعي')),
                ('hero_badge', models.CharField(default='🎓 منصة سودانية متكاملة للتعليم الجامعي', max_length=200, verbose_name='شعار Hero')),
                ('hero_title', models.CharField(default='بوابتك إلى الجامعات والمنح والتوثيق', max_length=300, verbose_name='عنوان Hero')),
                ('hero_description', models.TextField(default='نقدّم لك تجربة تعليمية متكاملة تجمع بين التقديم الإلكتروني، والمنح، وترتيب الرغبات، وتوثيق الشهادات.', verbose_name='وصف Hero')),
                ('contact_phone', models.CharField(default='+249 000 000 000', max_length=50, verbose_name='رقم الهاتف')),
                ('contact_email', models.EmailField(default='info@topsenier.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_address', models.CharField(default='السودان، أم درمان', max_length=200, verbose_name='العنوان')),
                ('whatsapp_number', models.CharField(default='+249000000000', max_length=50, verbose_name='رقم الواتساب')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='رابط لينكدإن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
