# Generated by Django 6.1.1 on 2026-09-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_add_default_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(default='منصة سودانية متكاملة تهدف إلى تسهيل رحلة الطالب الأكاديمية من التقديم للجامعات حتى استخراج الشهادات.', verbose_name='من نحن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_description',
            field=models.TextField(blank=True, default='', verbose_name='وصف المطور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='بريد المطور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_github',
            field=models.URLField(blank=True, default='', verbose_name='GitHub المطور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم المطور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_website',
            field=models.URLField(blank=True, default='', verbose_name='موقع المطور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_whatsapp',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='واتساب المطور'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_group',
            field=models.URLField(blank=True, null=True, verbose_name='مجموعة فيسبوك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_page',
            field=models.URLField(blank=True, null=True, verbose_name='صفحة فيسبوك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='إنستغرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_channel',
            field=models.URLField(blank=True, null=True, verbose_name='قناة تيليجرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_group',
            field=models.URLField(blank=True, null=True, verbose_name='مجموعة تيليجرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='تيك توك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (تويتر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='يوتيوب'),
        ),
    ]
