# Generated by Django 6.1.1 on 2026-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_sitesettings_about_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف المختصر')),
                ('image', models.ImageField(blank=True, help_text='المقاس المثالي: 1200×400 بكسل', null=True, upload_to='announcements/%Y/%m/', verbose_name='صورة الإعلان')),
                ('link', models.CharField(blank=True, help_text='مثال: /ranks/ أو https://example.com', max_length=300, verbose_name='الرابط')),
                ('button_text', models.CharField(blank=True, default='اعرف المزيد', max_length=50, verbose_name='نص الزر')),
                ('bg_color', models.CharField(blank=True, default='linear-gradient(135deg, #1e40af, #3b82f6)', help_text='CSS gradient أو لون عادي', max_length=50, verbose_name='لون الخلفية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ من')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
