# Generated by Django 6.1.1 on 2026-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='المقاس المثالي: 1920×1080 بكسل - حجم أقل من 1 ميجا', null=True, upload_to='hero/%Y/%m/', verbose_name='خلفية Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn1_icon',
            field=models.CharField(blank=True, default='fa-list-ol', help_text='مثال: fa-list-ol', max_length=50, verbose_name='أيقونة الزر الأول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn1_text',
            field=models.CharField(blank=True, default='رتّب رغباتك', max_length=50, verbose_name='نص الزر الأول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn2_icon',
            field=models.CharField(blank=True, default='fa-paper-plane', max_length=50, verbose_name='أيقونة الزر الثاني'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn2_text',
            field=models.CharField(blank=True, default='قدّم الآن', max_length=50, verbose_name='نص الزر الثاني'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_overlay_opacity',
            field=models.FloatField(default=0.6, help_text='من 0 (بدون طبقة) إلى 1 (طبقة معتمة تماماً)', verbose_name='شفافية الطبقة الداكنة'),
        ),
    ]
