# Generated by Django 6.1.1 on 2026-09-18 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='الرمز')),
                ('icon', models.CharField(default='fa-circle', help_text='مثال: fa-file-alt', max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'مدير عام'), ('team_lead', 'قائد فريق'), ('staff', 'موظف')], default='staff', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sections', models.ManyToManyField(blank=True, help_text='الأقسام التي يمكن لهذا المستخدم الوصول إليها', related_name='users', to='accounts.section', verbose_name='الأقسام المصرح بها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
