# Generated by Django 6.1.1 on 2026-09-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الرباعي')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف (واتساب)')),
                ('service_type', models.CharField(choices=[('high_school', 'استخراج شهادة ثانوية'), ('university', 'استخراج شهادة جامعية'), ('verify', 'توثيق شهادة'), ('translate', 'ترجمة معتمدة'), ('replace', 'بدل فاقد')], max_length=30, verbose_name='نوع الخدمة')),
                ('details', models.TextField(blank=True, help_text='أي معلومات مهمة عن الطلب', verbose_name='تفاصيل إضافية')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/certificate/%Y/%m/', verbose_name='صورة الشهادة')),
                ('national_id_file', models.FileField(blank=True, null=True, upload_to='certificates/national_id/%Y/%m/', verbose_name='الرقم الوطني')),
                ('status', models.CharField(choices=[('pending', 'جديد'), ('processing', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب شهادة',
                'verbose_name_plural': 'طلبات الشهادات',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
