# Generated by Django 6.1.1 on 2026-09-16 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الجامعة')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='الرابط المختصر')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('description', models.TextField(blank=True, verbose_name='نبذة عن الجامعة')),
                ('established_year', models.IntegerField(blank=True, null=True, verbose_name='سنة التأسيس')),
                ('university_type', models.CharField(choices=[('government', 'حكومية'), ('private', 'خاصة'), ('international', 'دولية')], default='government', max_length=20, verbose_name='نوع الجامعة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/', verbose_name='شعار الجامعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم الكلية/التخصص')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(blank=True, max_length=350, verbose_name='الرابط المختصر')),
                ('category', models.CharField(choices=[('medical', 'طبي'), ('engineering', 'هندسي'), ('humanities', 'أدبي'), ('administrative', 'إداري'), ('science', 'علوم'), ('technology', 'تقنية'), ('agriculture', 'زراعي'), ('law', 'قانون'), ('education', 'تربية'), ('art', 'فنون'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='التصنيف')),
                ('duration_years', models.IntegerField(default=4, verbose_name='مدة الدراسة (سنوات)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_faculties', to='universities.faculty', verbose_name='الكلية الأم')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['university', 'order', 'name'],
                'unique_together': {('name', 'university', 'parent_faculty')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='مثال: 2024', verbose_name='سنة القبول')),
                ('stream', models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي'), ('general', 'عام')], default='general', help_text='اتركه "عام" إذا كانت النسبة واحدة لجميع المساقات', max_length=20, verbose_name='المساق')),
                ('min_percentage', models.FloatField(help_text='النسبة المئوية المطلوبة للقبول', verbose_name='الحد الأدنى للنسبة (%)')),
                ('seats_available', models.IntegerField(default=0, help_text='0 = غير معروف', verbose_name='عدد المقاعد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='universities.faculty', verbose_name='الكلية/التخصص')),
            ],
            options={
                'verbose_name': 'متطلب قبول',
                'verbose_name_plural': 'متطلبات القبول',
                'ordering': ['-year', 'faculty'],
                'unique_together': {('faculty', 'year', 'stream')},
            },
        ),
    ]
