# Generated by Django 6.1.1 on 2026-09-18 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('status_change', 'تغيير الحالة'), ('export', 'تصدير')], max_length=20, verbose_name='الإجراء')),
                ('target_type', models.CharField(choices=[('application', 'طلب تقديم'), ('certificate', 'طلب شهادة'), ('contact', 'رسالة تواصل'), ('access_code', 'كود وصول'), ('user', 'مستخدم')], max_length=20, verbose_name='نوع الهدف')),
                ('target_id', models.IntegerField(verbose_name='رقم الهدف')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجل الأنشطة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='panel_activ_created_a87ed3_idx'), models.Index(fields=['user', '-created_at'], name='panel_activ_user_id_b7047c_idx')],
            },
        ),
    ]
