# Generated by Django 6.1.1 on 2026-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(choices=[('application', 'طلب تقديم'), ('certificate', 'طلب شهادة'), ('contact', 'رسالة تواصل'), ('access_code', 'كود وصول'), ('user', 'مستخدم'), ('announcement', 'إعلان')], max_length=20, verbose_name='نوع الهدف'),
        ),
    ]
