# Generated by Django 6.1.1 on 2026-09-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('accordion', 'Accordion (فتح/إغلاق)'), ('list', 'قائمة'), ('text', 'نص حر'), ('links', 'روابط')], default='accordion', max_length=20, verbose_name='نوع الكرت')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='وصف مختصر')),
                ('content', models.TextField(blank=True, help_text='يدعم HTML بسيط', verbose_name='المحتوى')),
                ('icon', models.CharField(blank=True, default='fa-circle', max_length=50, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_open_default', models.BooleanField(default=False, verbose_name='مفتوح افتراضياً')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كرت',
                'verbose_name_plural': 'الكروت',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القسم')),
                ('description', models.TextField(blank=True, help_text='يظهر تحت العنوان', verbose_name='وصف مختصر')),
                ('icon', models.CharField(default='fa-info-circle', help_text='مثال: fa-list-check', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#1e40af', max_length=20, verbose_name='اللون')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'أقسام الدليل',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: بدء التقديم الإلكتروني', max_length=200, verbose_name='العنوان')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='وصف مختصر')),
                ('date', models.DateTimeField(verbose_name='التاريخ والوقت')),
                ('icon', models.CharField(blank=True, default='fa-calendar-alt', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#dc2626', max_length=20, verbose_name='اللون')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='إظهار عداد تنازلي')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'موعد مهم',
                'verbose_name_plural': 'المواعيد المهمة',
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guide/images/%Y/%m/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guide.guidecard', verbose_name='الكرت')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuideLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرابط')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='وصف الرابط')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, default='fa-link', max_length=50, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='guide.guidecard', verbose_name='الكرت')),
            ],
            options={
                'verbose_name': 'رابط',
                'verbose_name_plural': 'الروابط',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuideListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='النص')),
                ('icon', models.CharField(blank=True, default='fa-check-circle', max_length=50, verbose_name='الأيقونة')),
                ('icon_color', models.CharField(blank=True, default='#10b981', max_length=20, verbose_name='لون الأيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guide.guidecard', verbose_name='الكرت')),
            ],
            options={
                'verbose_name': 'عنصر قائمة',
                'verbose_name_plural': 'عناصر القوائم',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='guidecard',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='guide.guidesection', verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='GuideVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('youtube_url', models.URLField(help_text='مثال: https://www.youtube.com/watch?v=XXXXX', verbose_name='رابط يوتيوب')),
                ('youtube_id', models.CharField(blank=True, help_text='يُستخرج تلقائياً من الرابط', max_length=20, verbose_name='معرف الفيديو')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='guide.guidecard', verbose_name='الكرت (اختياري)')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'الفيديوهات',
                'ordering': ['order'],
            },
        ),
    ]
