# Generated by Django 6.1.1 on 2026-09-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_code', models.CharField(max_length=20, unique=True, verbose_name='رقم الرسالة')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف (واتساب)')),
                ('service_type', models.CharField(choices=[('ranks', 'ترتيب الرغبات'), ('admission', 'التقديم الإلكتروني'), ('certificates', 'الشهادات والتوثيق'), ('scholarships', 'المنح الدراسية'), ('general', 'استفسار عام')], max_length=30, verbose_name='نوع الخدمة')),
                ('scope', models.CharField(choices=[('inquiry', 'استفسار عن خدمة'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح')], default='inquiry', max_length=20, verbose_name='نطاق الاستفسار')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('read', 'تم القراءة'), ('replied', 'تم الرد'), ('archived', 'مؤرشف')], default='new', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
