# Generated by Django 6.1.1 on 2026-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_code', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الرباعي')),
                ('seat_number', models.CharField(max_length=30, verbose_name='رقم الجلوس')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف (واتساب)')),
                ('state', models.CharField(choices=[('khartoum', 'الخرطوم'), ('jazeera', 'الجزيرة'), ('kassala', 'كسلا'), ('qadarif', 'القضارف'), ('red_sea', 'البحر الأحمر'), ('nile_river', 'نهر النيل'), ('north_kordofan', 'شمال كردفان'), ('south_kordofan', 'جنوب كردفان'), ('west_kordofan', 'غرب كردفان'), ('north_darfur', 'شمال دارفور'), ('south_darfur', 'جنوب دارفور'), ('west_darfur', 'غرب دارفور'), ('east_darfur', 'شرق دارفور'), ('central_darfur', 'وسط دارفور'), ('white_nile', 'النيل الأبيض'), ('blue_nile', 'النيل الأزرق'), ('sennar', 'سنار'), ('northern', 'الشمالية')], max_length=50, verbose_name='الولاية')),
                ('exam_year', models.IntegerField(verbose_name='سنة الامتحان')),
                ('stream', models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي')], max_length=20, verbose_name='المساق')),
                ('optional_subject', models.CharField(max_length=100, verbose_name='المادة الاختيارية')),
                ('application_type', models.CharField(choices=[('bachelor', 'بكالوريوس'), ('diploma', 'دبلوم')], default='bachelor', max_length=20, verbose_name='نوع التقديم')),
                ('failed_subjects', models.TextField(blank=True, help_text='مطلوب فقط في حالة التقديم للدبلوم', verbose_name='المواد الراسب بها')),
                ('preferences_file', models.FileField(upload_to='admission/preferences/%Y/%m/', verbose_name='ملف ترتيب الرغبات')),
                ('ranks_session_code', models.CharField(blank=True, help_text='إذا ربط الطالب نتيجة توقعه', max_length=50, verbose_name='كود جلسة التوقع')),
                ('status', models.CharField(choices=[('pending', 'جديد'), ('reviewed', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'طلب تقديم',
                'verbose_name_plural': 'طلبات التقديم',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
