# Generated by Django 6.1.1 on 2026-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True, verbose_name='كود الطلب')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='كود الوصول')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'مفعّل'), ('expired', 'منتهي'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('max_uses', models.IntegerField(default=20, verbose_name='عدد المحاولات')),
                ('current_uses', models.IntegerField(default=0, verbose_name='المستخدم')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
            ],
            options={
                'verbose_name': 'كود وصول',
                'verbose_name_plural': 'أكواد الوصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True, verbose_name='المعرف')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('activated_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='الكود المُفعّل')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='أول ظهور')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
            ],
            options={
                'verbose_name': 'استخدام زائر',
                'verbose_name_plural': 'استخدامات الزوار',
                'ordering': ['-last_seen'],
            },
        ),
    ]
