# Generated by Django 6.1.1 on 2026-09-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الطالب')),
                ('student_percentage', models.FloatField(verbose_name='نسبة الطالب (%)')),
                ('student_stream', models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي')], default='scientific', max_length=20, verbose_name='المساق')),
                ('session_code', models.CharField(help_text='كود فريد لمشاركة النتائج', max_length=50, unique=True, verbose_name='كود الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوقع')),
            ],
            options={
                'verbose_name': 'جلسة توقع',
                'verbose_name_plural': 'جلسات التوقع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProbabilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: عالية جداً', max_length=100, unique=True, verbose_name='اسم المستوى')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='الرمز')),
                ('min_difference', models.FloatField(help_text='الفرق بين نسبة الطالب والحد الأدنى (يُحسب كـ: نسبة الطالب - الحد الأدنى)', verbose_name='الحد الأدنى للفرق (%)')),
                ('max_difference', models.FloatField(blank=True, help_text='اتركه فارغاً إذا كان مستوى مفتوحاً (بدون حد أعلى)', null=True, verbose_name='الحد الأعلى للفرق (%)')),
                ('color', models.CharField(default='#6c757d', help_text='مثال: #28a745', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(blank=True, default='bi-circle', help_text='مثال: bi-check-circle', max_length=50, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=0, help_text='الأقل = الأعلى في العرض', verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مستوى احتمالية',
                'verbose_name_plural': 'مستويات الاحتمالية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الطالب (اختياري)')),
                ('student_percentage', models.FloatField(verbose_name='نسبة الطالب (%)')),
                ('student_stream', models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي')], default='scientific', max_length=20, verbose_name='المساق')),
                ('priority', models.IntegerField(help_text='رقم الرغبة (1، 2، 3...)', verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='universities.faculty', verbose_name='الكلية/التخصص')),
            ],
            options={
                'verbose_name': 'رغبة',
                'verbose_name_plural': 'الرغبات',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='الأولوية')),
                ('student_percentage', models.FloatField(verbose_name='نسبة الطالب')),
                ('min_percentage', models.FloatField(verbose_name='الحد الأدنى')),
                ('difference', models.FloatField(help_text='نسبة الطالب - الحد الأدنى', verbose_name='الفرق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.faculty', verbose_name='الكلية')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ranks.predictionsession', verbose_name='الجلسة')),
                ('probability_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranks.probabilitylevel', verbose_name='مستوى الاحتمالية')),
            ],
            options={
                'verbose_name': 'نتيجة توقع',
                'verbose_name_plural': 'نتائج التوقع',
                'ordering': ['priority'],
            },
        ),
    ]
